### ISSUE TITLE
Is it possible to position the modal to the bottom of the screen?

### ISSUE THREAD

**Issue by waynelei** [pradel/react-responsive-modal#102]
## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |    ^2.1.0     |
| React                  |     ^16.2.0    |
| browser                |     chrome    |

Is it possible to position the modal to the bottom of the screen instead of top or center. I know I can use 'little' to center the modal on screen, and default is on the top of screen. But any way I can put modal on the bottom of screen? Thanks

**Comment by pradel** [comment]
SO the modal is centered using flex all you have to do is to apply the following style to the `overlay` using inline styles or css classes `align-items: flex-end;`
let me know if it doesn't work :)

**Comment by waynelei** [comment]
The modal is still on the middle of the screen, not the bottom of screen, below is my code , thank you for any help

JS file
            <Modal
                open={this.props.open}
                onClose={() => this.props.onCloseModal()}
                showCloseIcon={false}
                little
                classNames={{ overlay: 'custom-overlay-location', modal: 'custom-modal-location' }}
            >
                <LocationDetail
                    marker={this.props.marker} />
            </Modal>


----------------
CSS file

.custom-modal-location {
    width: 400px;
    height: 200px;
}

.custom-overlay-location {
    align-items: flex-end;
}

**Comment by pradel** [comment]
I think it's because your css is overwrited buy the modal css.
Can you try to remove the little prop?

**Comment by waynelei** [comment]
i did, but get the same result

**Comment by pradel** [comment]
can you please reproduce the problem on codesandbox (you can use this template https://codesandbox.io/s/9jxp669j2o ) ?
