### ISSUE TITLE
Broken style on minify

### ISSUE THREAD

**Issue by mattiagecchele** [pradel/react-responsive-modal#103]
On React version 15.6.1 when building with Uglify enabled, the resulting bundle lacks the correct CSS Classes, and styling is broken.

Can you provide an already and properly minified version of the lib?

**Comment by pradel** [comment]
Hey, which version are you using?
Can you provide a reproducible example?

**Comment by cavarzan** [comment]
@pradel same here, using v3.0.0

![image](https://user-images.githubusercontent.com/3915288/39707748-a4a80234-51eb-11e8-9803-1df63dc45a3b.png)

Maybe the modules are injecting a hash on styleNames.

**Comment by pradel** [comment]
Are you using create-react-app or a custom webpack config to bundle your app?

**Comment by cavarzan** [comment]
`webpack`.
The css modules are enabled, but using `[local]` for css-loader, so it didn't change the node_modules style names.

**Comment by pradel** [comment]
if you are using the 3.0 version you don''t need a css loader the compiled version comes with the css already bundled. So the error must come from another part 🤔

**Comment by pradel** [comment]
Do you have a repo that reproduce the issue so I can investigate?

**Comment by pradel** [comment]
Feel free to reopen with more info if you still have this error
