### ISSUE TITLE
I have a .custom-modal and a .custom-overlay class but they are not overriding the default styles. How do I make sure they do?

### ISSUE THREAD

**Issue by lisahoong** [pradel/react-responsive-modal#107]
## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |    3.0.0     |
| React                  |    15.4     |
| browser                |    Chrome     |

**Comment by pradel** [comment]
Hey can you try the 3.0.1 version to see if the styles are now fixed?
