### ISSUE TITLE
Multiple modals problem

### ISSUE THREAD

**Issue by socker210** [pradel/react-responsive-modal#137]
## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |     3.0.2    |
| React                  |    16.4.0     |
| browser                |     Chrome 67.0.3396.87   |

Hi
I'm using react-responsive-modal with own project and i found some bug.
Maybe you can find this bug from "examples page => Multiple modals".

Here is step 
1. open first modal
2. open second modal
3. close second modal

then you can see the scrollable page.
So i edited some code
Before
`if (openedModals.length === 1)`
After
`if (openedModals.length === 0)`
and it work well.

Can i fix it?

**Comment by pradel** [comment]
Hey, you are right I can reproduce the bug, looks like there is something wrong with the current behavior. Will take a look at it when I have some time :)

**Comment by socker210** [comment]
@pradel Thank you so much :) :+1:
