### ISSUE TITLE
Modal enter animation

### ISSUE THREAD

**Issue by markronquillo** [pradel/react-responsive-modal#14]
Is it possible to change the onEnter animation of the modal?

**Comment by pradel** [comment]
Right now it's not possible but I will do it for the v2

**Comment by pradel** [comment]
It is now possible to change the enter and leave animation: see https://github.com/pradel/react-responsive-modal/blob/master/docs/src/examples/custom-animation.js for an example :)

**Comment by markronquillo** [comment]
Thanks man, if there is anything I can help you with in this project just let me know. I'm willing to contribute. Thanks
