### ISSUE TITLE
Question: Moving "button" After Modal Open

### ISSUE THREAD

**Issue by Tom-Gorup** [pradel/react-responsive-modal#155]
When I click on my button for my Modal, the button (which is an image), moves to the top of the page.

Glad to provide additional information if needed.

Appreciate the assist!

## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal | 3.0.3 |
| React                  | 16.4.1 |
| browser                | Chome (latest) |

<img width="1318" alt="screen shot 2018-07-02 at 11 00 58 am" src="https://user-images.githubusercontent.com/1697107/42171427-40661568-7de7-11e8-87c7-8e57c8a0e413.png">

<img width="1182" alt="screen shot 2018-07-02 at 11 01 01 am" src="https://user-images.githubusercontent.com/1697107/42171431-42d94f22-7de7-11e8-8a3d-a7df26fdce56.png">

# MyModal.js
```
import React from 'react';
import Modal from 'react-responsive-modal';
import MyLogo from '../LogoSelector';

export default class CenteredModal extends React.Component {
  state = {
    open: false,
  };

  onOpenModal = () => {
    this.setState({ 
      open: true 
    });
  };

  onCloseModal = () => {
    this.setState({ 
      open: false 
    });
  };

  render() {
    const { open } = this.state;
    
    return (
      <div className="MyModal">
        <MyLogo on_click={this.onOpenModal} myStyle="CenterLogo" color="white" />
        
        <Modal 
          open={open} 
          onClose={this.onCloseModal} 
          center
        >
          <iframe src="https://www.google.com" />
        </Modal>
      </div>
    );
  }
}
```

**Comment by pradel** [comment]
Hey, can you provide a codesandbox.io template (https://codesandbox.io/s/9jxp669j2o) or a repo to replicate the issue?

**Comment by pradel** [comment]
Okay so it's because when the modal is open these styles: `width: 100%; position: fixed; top: 0px; overflow: hidden;` are applied to the html element. You should try to center your element with flex instead it should fix the issue.
