### ISSUE TITLE
Modal does not display correctly, cuts off top part 

### ISSUE THREAD

**Issue by bau123** [pradel/react-responsive-modal#163]
### Summary:
When I create a modal with too much text or images, the modal does not give the correct scroll features and will cut the top part of the modal
### Steps to reproduce:

 1. create a modal
 2. a too many lines of text
 3.modal cannot display all text correctly and cuts off top part

| Tech                   | Version |
| react-responsive-modal |  3.0.3  |
| React                  |      16.3.2   |
| browser  Edge              |    38.14393.2068.0     |

**Comment by pradel** [comment]
Are you using the `center` prop on the modal?

**Comment by bau123** [comment]
@pradel Ah yes I used the center prop. Thanks
