### ISSUE TITLE
Override css of modal

### ISSUE THREAD

**Issue by guleus** [pradel/react-responsive-modal#170]
Hello,
how can i ovveride the css of the modal window?

## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |         |
| React                  |         |
| browser                |         |

**Comment by pradel** [comment]
Hey, you can take a look at this example https://github.com/pradel/react-responsive-modal/blob/master/docs/src/examples/custom-styling.js
