### ISSUE TITLE
Example using `container` prop

### ISSUE THREAD

**Issue by masiamj** [pradel/react-responsive-modal#171]
Thanks for your awesome work on this library! I saw the recent addition of the `container` prop. Can you please provide an example of how to use it? I'm having difficulties making the `Modal` render inside the container. Thanks!

**Comment by pradel** [comment]
Hey, you can find a example there: https://github.com/pradel/react-responsive-modal/releases/tag/v3.1.0

**Comment by pradel** [comment]
I just added an example that show how to use the `container` prop with react refs https://react-responsive-modal.leopradel.com/. Cheers!

**Comment by masiamj** [comment]
Awesome- thanks for that @pradel !
