### ISSUE TITLE
Modal inception - overflow hidden

### ISSUE THREAD

**Issue by amertak** [pradel/react-responsive-modal#2]
Hi,

I am using your awesome library for some time with no problems. Good job!

However, I found out, that opening modal in a modal is not behaving properly.
If you open a modal in a modal and the close it, it will reset the "overflow: hidden" style on body which is not proper behaviour as it should keep the hidden property there until you close the fist modal.

Does it make sense?

Thanks,
David

**Comment by pradel** [comment]
Hi, yeah it's normal, I haven't done it! I would happily accept a pull request for that 😃

**Comment by amertak** [comment]
Will look into it, no problem :)

**Comment by amertak** [comment]
#4 Look at it :)

**Comment by pradel** [comment]
Published in 1.4.1 thanks!
