### ISSUE TITLE
Exception onClick on modal

### ISSUE THREAD

**Issue by dmfilipenko** [pradel/react-responsive-modal#20]
In this line https://github.com/pradel/react-responsive-modal/blob/f390bf2f4e4e08d8f15bd82e981f943639c67352/src/modal.js#L63
I've got an exception. 
Its' happened in the case when I'm clicking on the svg element. classList it's an object, not string. it include two properties
![Img](https://cldup.com/psSI0fxyUf-3000x3000.png)

**Comment by pradel** [comment]
Hey, can you provide a reproductible example on codesandebox please? (you can take this template https://codesandbox.io/s/9jxp669j2o).
Thanks!

**Comment by angrypie** [comment]
Actually your example does not work

**Comment by pradel** [comment]
It is working for me, can you see if there is an error in the console?

**Comment by angrypie** [comment]
After I close modal window I see "TypeError
e.target.className.split is not a function."

**Comment by pradel** [comment]
Which browser, version are you using?

**Comment by angrypie** [comment]
Latest version in Safari and Google Chrome gives same result.

**Comment by pradel** [comment]
Thanks, I was able to reproduce the issue.  I will push a fix soon.

**Comment by ken210** [comment]
I'm also having this issue. Just to add more data to it, pressing ESC key closes the modal and don't throw any errors.

**Comment by pradel** [comment]
It should be fixed in 1.9.4 👍 
Tell me if it's not working for you!
