### ISSUE TITLE
Fixed navbar and open modal.

### ISSUE THREAD

**Issue by GTOsss** [pradel/react-responsive-modal#201]
I use navbar with position: fixed. When open modal, my navbar dont have padding right. Perhaps if the tag html or bopy had a some className, I would be able to use nesting styles to fix the problem. For example (when modal open):

```
<html class="modal-responsive-open" style="width: calc(100% - 17px); position: fixed; top: -535.2px; overflow: hidden;" >

 .modal-responsive-open .my-fixed-navbar {
  padding-right: 17px;
}
```

**Comment by pradel** [comment]
Feel free to reopen the issue if you need more help :)
