### ISSUE TITLE
Scroll Issue with big modal

### ISSUE THREAD

**Issue by pravin-d** [pradel/react-responsive-modal#202]
| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |     latest    |
| React                  |      latest   |
| browser                |     chrome    |

When using big modal, sometime the scrolling does not work. The scroll bar is present and the modal can be scrolled by dragging the scrollbar. However mouse wheel events gets ignored.
The issue can be reproduced on demo site for this repo.
Position the Big Modal button in some position of the screen and invoke the modal. Sometimes the scrolling using mousewheel gets stuck.

**Comment by pradel** [comment]
Hum .. that's weird I never encountered this issue 🤔 Does anyone also have this issue?

**Comment by RedTn** [comment]
I've ran into this issue before as well, React 15 on chrome browser with latest react responsive modal 3.3.
I'll see if I can create a reproducible demo some time

**Comment by rafaponieman** [comment]
I ran into the same issue. Couldn't pinpoint the reason though.

**Comment by rafaponieman** [comment]
Adding more information:

Any DOM modification after the modal opens appears to fix the scroll issue temporarily (until the modal is closed and re-opened). If I delete an element from the developer tools, or even if I change a CSS rule, it starts working again.

Live example: https://www.peaksport.com.ar/es/ you'd have to sign up and go to "Mi cuenta"  > "Mis direcciones" and add a new address by clicking on "Agregar dirección".

**Comment by RedTn** [comment]
I have no idea why this works, but if I wrap the modal content with https://github.com/utatti/perfect-scrollbar it seems to scroll on modal load ¯\_(ツ)_/¯

**Comment by RedTn** [comment]
> Just add `transform: translateZ(0);` to overlay's styles.

Thanks! This works but I'm worried what the implications are, it seems to force the browser to create a new layer for the modal. Did you ever track down what was causing the issue?

**Comment by AlexCSR** [comment]
There shouldn't be any implications, only if you decide to add some animations using `transform` it may cause some troubles.
Honestly I can't find any logical reason causing that effect. It looks like an overlay doesn't have focus but it's not true. It's very similar to an old IE's "hasLayout" bug, if you know what I'm talking about :)

So maybe it's really just a browser bug. But I'm not sure and I'd be glad to know why that happens if anyone knows.

**Comment by Mujaddadi** [comment]
I got the scrolling issue but not when the modal is open but when it is closed. It freezes the scrolling of the page.

**Comment by zanehiredevs** [comment]
Just ran into this issue with a long modal and translate fix worked for me

**Comment by pradel** [comment]
Hey all, I just published v6.0.0, this package is now using body-scroll-lock instead of no-scroll to solve all the scroll related issues.
