### ISSUE TITLE
Feature: Add prop for adding an ID to the modal

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [pradel/react-responsive-modal#227]
Hello,

I just ran into an issue where it would be nice for me to be able to add an ID to the modal by passing an "id" prop, like so: `<ReactModal id="my-modal">content</ReactModal>`

Is this a feature that you would be okay with adding to the library?

**Comment by pradel** [comment]
Yes feel free to submit a pull request for that :)

**Comment by ajinkyashukla29** [comment]
I created a pull request for this. Please let me know if any changes.
https://github.com/pradel/react-responsive-modal/pull/275

**Comment by Bosch-Eli-Black** [comment]
Thanks, @ajinkyashukla29!

**Comment by pradel** [comment]
Published as v3.6.0 thanks @ajinkyashukla29 🚀
