### ISSUE TITLE
can't see styling effect

### ISSUE THREAD

**Issue by jcabrerazuniga** [pradel/react-responsive-modal#23]
I am importing your Modal object using:

    import Modal from 'react-responsive-modal';

and using it with:

            <Modal open={this.state.openModal4task} onClose={this.onCloseModal} little={false}  classNames={{ overlay: 'wlcustom-overlay', modal: 'wlcustom-modal' }}>
				
                   <MyReactComp/>
				
            </Modal>

my CSS is called and has:

    .wlcustom-overlay {
        background: rgba(36, 123, 160, 0.7) !important;
    }
    .wlcustom-modal {
          background: #b2dbbf !important;
          max-width: 1400px !important;
          width: 100%;
    }

yet, I can not see any change....
Am I missing something?
Thx

**Comment by pradel** [comment]
Which version do you use?
Did you import the css file?
