### ISSUE TITLE
TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by imletaconnoux** [pradel/react-responsive-modal#24]
Hi!

I was using the react-responsive-modal in my project earlier and it worked. In the past hour I've been getting a "TypeError: Cannot call a class as a function". In my console I got this warning, "index.js:2177 Warning: The <Jss(Modal) /> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change Jss(Modal) to extend React.Component instead."

I installed 'react-responsive-modal' and it's in my package.json.

When I remove the Modal element from my code, I no longer have any issues. Any thoughts on how to fix?

My code is as follows:

`import React from 'react';
import CommentForm from './CommentForm';
import CommentList from './CommentList';
import Modal from 'react-responsive-modal';
import '../../App.css'

class ImageItem extends React.Component{

  constructor(){
    super()
    this.state = {
      open: false
    }
  }

  openModal = () => {
    this.setState({open: true})
  }

  closeModal = () => {
    this.setState({open: false})
  }

  render(){
    let link
    if (this.props.image.cover) {
      link = `https://i.imgur.com/${this.props.image.cover}.jpg`
    } else if (this.props.image.link) {
      link = this.props.image.link
    }
    return(

        <div className="column">
          <div className="Image-container">
            <img aligned="center" src={link} alt={this.props.image} onClick={this.openModal}/>
          </div>
          <Modal open={this.state.open} onClose={this.closeModal}>
            <p>Image Title: {this.props.image.title} </p>
            <div className="Modal-container">
              <img aligned="center" src={link} alt={this.props.image} />
              <CommentList comments={this.props.comments}/>
              <CommentForm image={this.props.image.id}/>
            </div>
          </Modal>
        </div>

      )

  }
}

export default ImageItem
`

**Comment by pradel** [comment]
Hi,
Which version do you use?
Can you provide a reproductible example?
