### ISSUE TITLE
SSR Compatibility

### ISSUE THREAD

**Issue by denny64** [pradel/react-responsive-modal#240]
Any plans on making this library SSR compatible?

**Comment by pradel** [comment]
Hey, what problem do you encounter with ssr?
The library should work for it.

**Comment by pradel** [comment]
Closing this one, @denny64 feel free to reopen it if you have an issue with ssr and this package.

**Comment by maLikiz** [comment]
Is it possible to render `Modal` open on the server side?
At the moment I am getting an error setting `open` prop as `true` (version 5.0.2):
```
Target container is not a DOM element.
```

**Comment by pradel** [comment]
@maLikiz @facundocoto thanks for reporting the issue, should be fixed in v5.2.1 :)
