### ISSUE TITLE
Modal shows this annoying white background.

### ISSUE THREAD

**Issue by H27-VEN** [pradel/react-responsive-modal#257]
I am using this modal in one of my projects and I have this issues with white background that appears behind the overlay.

screenshot 1
![image](https://user-images.githubusercontent.com/30732258/50570540-bb0ddb80-0db5-11e9-947e-74475d41ff58.png)

screenshot 2
![image](https://user-images.githubusercontent.com/30732258/50570556-1b048200-0db6-11e9-8dd7-b0b2c7a4a79d.png)

You can easily see a white background appearing in screenshot 2.

it is seen in chrome, firefox and edge

**Comment by pradel** [comment]
I am closing this issue as it's quite old and the lib received some major updates, feel free to reopen if it's still happening in the last version
