### ISSUE TITLE
Background is blank when using with next.js

### ISSUE THREAD

**Issue by sheunglaili** [pradel/react-responsive-modal#263]
The overlay background will become blank when using with next.js ,
 tried to set container and styling but don't work 

## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |   3.5.1      |
| React                  |    16.6.3     |
| browser                |     chrome    |

**Comment by sheunglaili** [comment]
figured out what happend. When open modal , position:fixed style is append to the <html> tag . Causing content disappear.

**Comment by heshamelmasry77** [comment]
i have have similar problem when i open some css get to the html tag and then when i close sometimes it disappear sometime not 

<img width="734" alt="Screenshot 2019-03-08 at 23 30 18" src="https://user-images.githubusercontent.com/15607302/54056911-2632be80-41fa-11e9-955c-f04d02d96d1a.png">
