### ISSUE TITLE
Remove default styling from modal

### ISSUE THREAD

**Issue by milesalex** [pradel/react-responsive-modal#27]
I'm trying to override the padding using classes. Currently, this isn't working :/

![image](https://user-images.githubusercontent.com/421362/34224660-991a7512-e591-11e7-8e1e-ccd81b4d8575.png)

**Comment by pradel** [comment]
How are you handling your styles?

**Comment by pradel** [comment]
If you are using jss you can take a look at this link https://github.com/cssinjs/jss/blob/master/docs/setup.md#specify-dom-insertion-point

**Comment by milesalex** [comment]
I'm trying to override it with classes

```
<Modal classNames={{ overlay: 'custom-overlay', modal: 'mw6' }} open={this.state.open} onClose={this.onCloseModal} little>
  <h2>{this.state.exchangeModal}</h2>
</Modal>
```

**Comment by pradel** [comment]
how do you generate your styles with jss or regular css files?

**Comment by milesalex** [comment]
Just using classes. Tachyons. Io

**Comment by pradel** [comment]
So you have two ptions:
- you will need to add https://material-ui-1dab0.firebaseapp.com/customization/css-in-js/#css-injection-order in top of your Tachyon css file
- you can also use the css only version of this module https://github.com/pradel/react-responsive-modal#usage-with-css

**Comment by pradel** [comment]
Did this solve your issue?

**Comment by joysword** [comment]
Hi @pradel, the last link you posted is not working (#usage-with-css), and the material ui documentation on css injection order is now at: https://material-ui.com/styles/advanced/#css-injection-order

**Comment by Samesh** [comment]
Hey, using the inline styles worked for me

`<Modal
                open={!!router.query.postId}
                onClose={() => router.back()}
                styles={{
                    modal: {margin: 0},
            }}
            >`
