### ISSUE TITLE
Content in a div element or without any container is overlapped by the close button.

### ISSUE THREAD

**Issue by karlitos** [pradel/react-responsive-modal#276]
## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |    3.5.1     |
| React                  |    16.4.2     |
| browser                |    Chrome 71     |

I found this cool project, installed it, set-up the Modal with some generic content (Lorem ipsum ...), opened it in a browser and the closing button was overlapping my content. Hmm ... wrapped it in a div and ... again! I took me some time to realize that all the examples are using elements with default pre-defined top margin (h2, p) which compensates for the close button size.

Example: https://codesandbox.io/s/olvjzr86x9

So actually If I need a generic modal container to put there whatever I feel like I need to wrap it in some container compensating for the close-button size. I actually expected, that the modal would do this for me.

I think it would be very valuable feature to just pass the close button size via the props without having to care about additional styling to compensate it.

**Comment by pradel** [comment]
Hey @karlitos sorry for the late response, you actually have a `closeIconSize` prop that you can pass to the modal.

**Comment by karlitos** [comment]
Hi, thanks but how does this help in my case ? Please see updated example: https://codesandbox.io/s/kmn4v29ko3

**Comment by pradel** [comment]
In your example you don't have any margin but for example if you add a `p` tag around your content the close icon will not anymore overlap the text.
Usually in a modal you have a title (which most of the time have some top margin) so that's why I decided to not add some additional margin for the close icon.

**Comment by karlitos** [comment]
Ok, but this is what my bug-report was essentially about. Yes, you can wrap your content in an element  and often you have a title in your modal. But the bare minimal modal example - just text and the close button does not work and might be misleading. I didn't expect that. At least it shall be explained in the documentation, that the modal shall not be used with text not wrapped in an element.

**Comment by pradel** [comment]
That's a good point 👍

**Comment by pradel** [comment]
Finally added to the docs, will be published soon
