### ISSUE TITLE
ARIA Tags

### ISSUE THREAD

**Issue by red-coat** [pradel/react-responsive-modal#283]
Hello, any support for adding aria tags? eg:

`<Modal

          open={open}
          onClose={this.onCloseModal}
          role="dialog"
          aria-labelledby="dialogTitle"
          aria-describedby="dialogDesc"
        >
          <Text id="dialogTitle"><strong>Your title goes here</strong></Text>
          <Text id="dialogDesc">
          </Text>
        </Modal>`

**Comment by pradel** [comment]
Not for now but happy to accept a pull request that add support :)

**Comment by red-coat** [comment]
sent a PR bro, thanks!

**Comment by yjacobowitz** [comment]
It seems like there are some failing tests, any updates on this issue?

**Comment by pradel** [comment]
Fixed in v4.0.0
