### ISSUE TITLE
styles don't go away from the html tag next js

### ISSUE THREAD

**Issue by heshamelmasry77** [pradel/react-responsive-modal#301]
i have a wierd problem. the modal adds some inline css to the html tag 
<img width="734" alt="Screenshot 2019-03-08 at 23 30 18" src="https://user-images.githubusercontent.com/15607302/54057047-8590ce80-41fa-11e9-8678-6d8856dc5f93.png">

to process the issue : 
1. open the modal and then i close it then redirectly to another page.
2. i have another modal on another place. I open it.
3. i close it 
4. i go back to the first modal page 
5. i open it again and i navigate
6. the inline style don't go even if the modal closed.

**Comment by bill-vatomic** [comment]
This is happening to me as well, and causing issues, as the page becomes unscrollable while the inline styles are on the <html> element.

**Comment by pradel** [comment]
This one looks related to #239, I will try to find some time to take a look why the onExited event is not called when the route is changed.

**Comment by pradel** [comment]
Fixed in v4.0.0
