### ISSUE TITLE
How to add custom classname in modal

### ISSUE THREAD

**Issue by anupmishra203** [pradel/react-responsive-modal#310]
I am using react-responsive-modal, however I am unable to add the own custom class.

<Modal
              open={open}
              onClose={this.onCloseModal}
              showCloseIcon={false}

            >

**Comment by pradel** [comment]
You can use the `classNames` property for that. take a look at this example https://github.com/pradel/react-responsive-modal/blob/master/docs/examples/custom-styling.js

**Comment by WalidKurchied** [comment]
Take a look at the docs under classNames you can target different elements of the entire pop up modal for example I used `classNames={{modal: "modal"}}` to give my modal a class name of modal.
