### ISSUE TITLE
Modal With Few Contents Is Always Centered Even If Setting Center Props To False

### ISSUE THREAD

**Issue by jovanidash21** [pradel/react-responsive-modal#315]
## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal | 4.0.0 |
| React                  | 16.6.3 |
| browser                | Chrome 74.0.3729.131 |

Hello and Good day.
I'm using react-responsive-modal for my own project and I noticed some bug. My modal with few contents is always centered even if I add center={false} on the Modal props `<Modal open={open} onClose={this.onCloseModal} center={false}>`

**Comment by pradel** [comment]
Fixed in v4.0.1
