### ISSUE TITLE
Different overlay and content transition

### ISSUE THREAD

**Issue by majid-amiri** [pradel/react-responsive-modal#319]
Hi,
I wanna know if there is any way that overlay transition be different from content transition? For example, overlay transition would be "fade-in" and content "from bottom to up".
The current behavior is that there are 4 style classes (transitionEnter-transitionEnterActive-transitionExit-transitionExitActive) that is used for both overlay and content.

Here's my transition styles:

```
.transitionEnter {
  transform: translateY(100vh);
}
.transitionEnterActive {
  transform: translateY(0);
  transition: transform 500ms cubic-bezier(0.23, 1, 0.32, 1);
}
.transitionExit {
  transform: translateY(0);
}
.transitionExit {
  transform: translateY(100vh);
  transition: transform 500ms cubic-bezier(0.23, 1, 0.32, 1);
}
```

## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |     ^3.6.0    |
| React                  |    ^16.8.6     |
| browser                |     Chrome 74.0.3729.157    |

**Comment by pradel** [comment]
Hum I never tried to do that but maybe you can try to target the sub elements? eg:
```
.transitionEnter .modal {
  transform: translateY(100vh);
}
.transitionEnter .overly {
  // other animation
}
```

**Comment by majid-amiri** [comment]
> Hum I never tried to do that but maybe you can try to target the sub elements? eg:
> 
> ```
> .transitionEnter .modal {
>   transform: translateY(100vh);
> }
> .transitionEnter .overly {
>   // other animation
> }
> ```

I tried that but the transition is not working. I checked your code, you are calling CSSTransition before the place you are using CSS classes, so we can't rely on CSS class to handle that.

```
<Portal container={container}>
        <CSSTransition
          in={open}
          appear
          classNames={{
            appear: classNames.transitionEnter || classes.transitionEnter,
            appearActive:
              classNames.transitionEnterActive || classes.transitionEnterActive,
            enter: classNames.transitionEnter || classes.transitionEnter,
            enterActive:
              classNames.transitionEnterActive || classes.transitionEnterActive,
            exit: classNames.transitionExit || classes.transitionExit,
            exitActive:
              classNames.transitionExitActive || classes.transitionExitActive,
          }}
          timeout={animationDuration}
          onEntered={this.handleEntered}
          onExited={this.handleExited}
        >
          <div
            className={cx(
              classes.overlay,
              center ? classes.overlayCenter : null,
              classNames.overlay
            )}
            onClick={this.handleClickOverlay}
            style={styles.overlay}
            id={overlayId}
          >
...
```

**Comment by jromme** [comment]
For the people who are still looking to have their own CSS animations: 

You can set the animationDuration to 0 and then assign a class that has its own custom css transition/animation. 

It's dirty but it works.

**Comment by pradel** [comment]
Hey all sorry for not responding earlier, I added an example that show how you can do this: https://react-responsive-modal.leopradel.com/examples#custom-animation (check the second example).

This issue has been closed in the v5 of this package.
📖 You might want to check the **[announcement post](https://www.leopradel.com/blog/react-responsive-modal-v5)** containing the migration guide :)
