### ISSUE TITLE
Help changing animations

### ISSUE THREAD

**Issue by KingZee** [pradel/react-responsive-modal#320]
https://react-responsive-modal.leopradel.com/examples#custom-animation

This example shows how to include custom animation, but it isn't clear to me how is `customAnimationStyles` declared.

I'm using latest version of nextjs. This code causes an error when I run it : 
```javascript
import Modal from 'react-responsive-modal';
    
const [modalState,setModal] = useState(false);

const Page= () => {
    const modalstyle = {
    transitionEnter : {
        transform: "translateY(100vh)"
        },
    transitionEnterActive : {
        transform: "translateY(0)",
        transition: "transform 500ms cubic-bezier(0.23, 1, 0.32, 1)"
        },
    transitionExit : {
        transform: "translateY(0)"
        },
    transitionExit : {
        transform: "translateY(100vh)",
        transition: "transform 500ms cubic-bezier(0.23, 1, 0.32, 1)"  
        }
    };

    function closeModal(){
        setModal(false);
    }

    return (
        <div>
        <Modal classNames={{
          transitionEnter: modalstyle.transitionEnter,
          transitionEnterActive: modalstyle.transitionEnterActive,
          transitionExit: modalstyle.transitionExitActive,
          transitionExitActive: modalstyle.transitionExitActive,
        }} open={modalState} onClose={closeModal} center>
            <h2>Simple centered modal</h2>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam
            pulvinar risus non risus hendrerit venenatis. Pellentesque sit amet
            hendrerit risus, sed porttitor quam.
            </p>
        </Modal>    
            <p>My text</p>
        </div>
    )
};

export default Page;
```

**Comment by pradel** [comment]
I see, you are trying to pass inline styles to the classNames property. The docs are not really clear but you have to declare the class names in a css file or using css-in-js and pass the class names as an object of string.

The example is importing this css file https://github.com/pradel/react-responsive-modal/blob/master/docs/examples/custom-animation.css

**Comment by KingZee** [comment]
Thanks for your answer, unfortunately I still couldn't figure it out. 

I'm using nextjs, and [next-css](https://github.com/zeit/next-plugins/tree/master/packages/next-css), but if I wanted to replicate your example I'd need to use css modules, which will unfortunately break all my other declarations as I'm using bootstrap which styles depending on elements' className.

In addition to this I still couldn't figure out how to make the overlay invisible, independently from the modal itself, which is an issue for both this and react-modal. Thanks again for your help.

**Comment by pradel** [comment]
You don't need to use css modules, you just have to import the css file and call the modal like this:
```js
<Modal classNames={{
          transitionEnter: 'transitionEnter',
          transitionEnterActive: 'transitionEnterActive',
          transitionExit: 'transitionExitActive',
          transitionExitActive: 'transitionExitActive',
        }} open={modalState} onClose={closeModal} center>
            <h2>Simple centered modal</h2>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam
            pulvinar risus non risus hendrerit venenatis. Pellentesque sit amet
            hendrerit risus, sed porttitor quam.
            </p>
        </Modal>
```

**Comment by pradel** [comment]
If you want to hide the overlay you can just overwrite the overlay style using the classNames props and providing an `overlay` custom class name

**Comment by KingZee** [comment]
Thanks! But I am correctly setting the css for both the overlay and the modal differently, I just don't know how to make it's "cascading" styles not "cascade". I want to display my modal without an overlay.

```
    const modalstyle = {
        overlay : {
            "backgroundColor" : "red",
            "opacity" : "0.2"
        },
        modal : {
            "opacity" : "1"
        }
    }
```
This doesn't work, nor does display:none, I'm not sure how to get around this.

**Comment by pradel** [comment]
If you want to make the overlay disappear you can use this style on the overlay `    background: rgba(0, 0, 0, 0);`
