### ISSUE TITLE
focusTrapped messes with modal animations if applied to parent and child

### ISSUE THREAD

**Issue by red-coat** [pradel/react-responsive-modal#321]
Hey man great to see you implemented ARIA nice work!
Since updating i noticed my modal animations were messed up, i realise now the problem is focusTrapped being true by default, but im not sure why this is the problem. Below are my animation styles as you can see i want to fade in the overlay and have the immediate child div (modal content) animate up, if the animations are all on the parent it works fine, but obviously an opaque overlay animating up with the content looks weird.
Anyway i thought i'd let you know, ive disabled focusTrapped as a fix for now, ill have a look into the issue myself when i get more than a minute

`.upsellmodal--enter {
    opacity: 0;
    .upsellmodal__content {
      transform: translateY(550px);
    }
  }
  .upsellmodal--enteractive {
    opacity: 1;
    .upsellmodal__content {
      transform: translateY(0);
    }
  }
  .upsellmodal--exitactive {
    opacity: 1;
    .upsellmodal__content {
      transform: translateY(0);
    }
  }
  .upsellmodal--exitactive {
    opacity: 0;
    .upsellmodal__content {
      transform: translateY(550px);
    }
  }`

**Comment by red-coat** [comment]
So it appears that if the distance between your first focusTrapped element and the initial position of your transformY exceeds your viewport dimensions you will see the bug i was getting.
To get around the issue i used focuTrapped options to target the close button for initial focus and then wrapped my transform animation in a max height media query so it wont animate up if the screen dimensions do not allow.

**Comment by pradel** [comment]
As we are now using css animations, this should be fixed in the last version :)
Feel free to reopen if it's not, thanks.
