### ISSUE TITLE
Using css pseudo-classes (:hover :focus) to style the modal

### ISSUE THREAD

**Issue by karlitos** [pradel/react-responsive-modal#322]
## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |  4.0.0       |
| React                  |    16.6.0     |
| browser                |     Chrome 74.0    |

I would like to style the close button with some border and outline on focus. It worked when using external css and setting the __classNames.closeButton__ property but I prefer to have the styles in my code. So I wonder how to use the __styles__ property to achieve this.

I know, that using pseudo-classes with inline-styling is quite hard with react, but it would be great if you modal would also recognize properties like __classNames.closeButtonHover_ or __classNames.modal_focus_ or similar

**Comment by smollweide** [comment]
Also it's not yet possible to use mediaQueries.

**Comment by pradel** [comment]
@karlitos, as @smollweide said you can use the `classNames` prop for this.

**Comment by pradel** [comment]
@smollweide thanks for helping!
