### ISSUE TITLE
Feature request: Add property for a callback fired when the enter key is pressed.

### ISSUE THREAD

**Issue by karlitos** [pradel/react-responsive-modal#323]
## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |  4.0.0       |
| React                  |    16.6.0     |
| browser                |     Chrome 74.0    |

I tried to implement a simple wrapper around the `react-responsive-modal` with text, submit and abort buttons. Even if I use the `autofocus` property on the abort button the __submit__ callback is being fired, when the user press enter. This is unfortunate, because it is a modal dialog for: _"Are you sure you want to delete the item ?"_ and the default behavior should be vice versa. Maybe there is something wrong with my code, but it would be great to have a possibility to define, what happens, when the user hits enter.

My code looks like:
```javascript
/**
 * Define some styled components for this component
 */

const ModalButtonContainer = styled.div`
	float: right;
`;

const ModalContentContainer = styled.div`
	margin: 1em 0;
`;

const ModalSubmitButton = styled.button`
	margin-right: 1em;
	outline: 0;
`;

const ModalDenyButton = styled.button`
	outline: 0;
`;

const SimpleSubmitModal = (props) => {

	return (
		<Modal open={props.showModal}
			   showCloseIcon={false}
			   onClose={props.handleDeny}
			   focusTrapped={true}
			   center>
			<ModalContentContainer>
				{props.message}
			</ModalContentContainer>
			<ModalButtonContainer>
				<ModalSubmitButton onClick={props.handleSubmit}>
					Ok
				</ModalSubmitButton>
				<ModalDenyButton className='error' onClick={props.handleDeny} autoFocus>
					Cancel
				</ModalDenyButton>
			</ModalButtonContainer>
		</Modal>
	);
};

export default SimpleSubmitModal;
```

**Comment by pradel** [comment]
Hey, sorry for not getting back to this one earlier, I think this should be handled by your application. If we add an event for the enter key, we would have to add one for every other key. So it makes more sense that the user handles it in his own code.
