### ISSUE TITLE
 Error: You can't have a focus-trap without at least one focusable element

### ISSUE THREAD

**Issue by bill-vatomic** [pradel/react-responsive-modal#330]
## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |   4.0.1      |
| React                  |    16     |
| browser                |    Chrome     |

Since the latest update to 4.0.0, which fixed another bug I was experiencing, I am now totally unable to use this package because each time I get the following error when I try to open a modal:

`Error: You can't have a focus-trap without at least one focusable element`

Does anyone know what might cause this? I'm going to have to find a new package if I can't figure this out.

**Comment by pradel** [comment]
In the new version `focusTrapped` is true by default you can set it to false to remove this error.
It's because you don't have any focusable elements in your modal, eg a button

**Comment by pradel** [comment]
I will need to update the docs to clarify this error

**Comment by bill-vatomic** [comment]
Ah okay, I see in the changelog that focusTrapped is true. Thanks for the update! I will give that a shot now.

**Comment by bill-vatomic** [comment]
Awesome! Working great now! Thanks!
