### ISSUE TITLE
Can I change the modal background color?

### ISSUE THREAD

**Issue by usama-asfar** [pradel/react-responsive-modal#332]

**Comment by pradel** [comment]
Check the "Custom styling" example https://react-responsive-modal.leopradel.com/examples#custom-styling

**Comment by usama-asfar** [comment]
> Check the "Custom styling" example https://react-responsive-modal.leopradel.com/examples#custom-styling

Please help me I don't understand how to style this?

```
classNames={{
          overlay: customStyles.customOverlay,
          modal: customStyles.customModal,
        }}
```

**Comment by pradel** [comment]
Write a custom css file:
```
.customOverlay {
  background: rgba(36, 123, 160, 0.7);
}
.customModal {
  background: #b2dbbf;
  max-width: 500px;
  width: 100%;
}

```
then pass the classNames to the modal
```
classNames={{
          overlay: "customOverlay",
          modal: "customModal",
        }}
```

**Comment by abdul-elah-js** [comment]
what about the containing div inside the modal ? It's driving me crazy I can't set a custom dynamic style to it ..

**Comment by rohitkumarsa** [comment]
please tell me,  how to make modal popup overlay background color change in react js

**Comment by rohitkumarsa** [comment]
example :- http://72.167.42.251:5000/#/exchange
