### ISSUE TITLE
Bug when opening modals in safari browser

### ISSUE THREAD

**Issue by 3andy** [pradel/react-responsive-modal#333]
So i have just noticed this issue, it's a little Intermittent, I'm sure it wasn't happening before however you can experience the issue by loading up the examples in safari browser and toggling modals open: https://react-responsive-modal.leopradel.com/examples
The page seems to jump to the top and back again in an instance.
I've tried reverting to 3.6.0 but the problem still persists.

Im struggling to figure this one out all other browsers seem fine, any help would be much appreciated!
When looking in the DOM i swear i can see a pseudo element of ::before being added to the html tag, but its so quick its hard to observe properly.

**Comment by red-coat** [comment]
Looks as though it is related too this: https://github.com/davidtheclark/no-scroll/issues/9

**Comment by red-coat** [comment]
scrollBlock={false} is totally ignored

**Comment by red-coat** [comment]
So that didn't actually fix it and after much investigation it turns out its a known bug in IOS Safari only where the html and body elements do not respect overflow. See here for more info: https://bugs.webkit.org/show_bug.cgi?id=153852
Looks like its been fixed going off last messages, maybe it'll be in the next release of Safari

**Comment by ddtch** [comment]
Faced with the same issue. When I'm scrolling page fast, and then responsive modal triggers open. I can not interact with it.

**Comment by websocket98765** [comment]
Using `react-responsive-modal` v5 + Safari v13 has an issue in which long modals (with lots of content) open already scrolled to the bottom of the modal. I haven't found a solution for this yet.

**Comment by pradel** [comment]
Hey all, I just published v6.0.0, this package is now using body-scroll-lock instead of no-scroll to solve all the scroll related issues.
