### ISSUE TITLE
FocusTrap introduces unnecessary <div> element

### ISSUE THREAD

**Issue by Letrab** [pradel/react-responsive-modal#352]
## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |  4.0.1       |
| React                  |    16.9     |
| browser                |    Chromium     |

When having `focusTrapped` enabled (which is default) a new and unnecessary div element is being introduced in the children of the modal div container.

For me this is unwanted as it messes up my styling, and I cannot access classNames or styling of this div. It also defeats the purpose of using React.Fragments, exactly to avoid this.

See attached images, with using sample code https://codesandbox.io/s/9jxp669j2o  :
https://imgur.com/a/ihNFUGc

I think it can be easily avoided by moving the FocusTrap element to wrap around the full modal-div. Which is also recommended actually according to the `focus-trap-react` documentation:

> You wrap any element that you want to act as a focus trap with the <FocusTrap> component. <FocusTrap> expects exactly one child element which can be any HTML element or other React component that contains focusable elements.
> For example: 
> ```
> <FocusTrap>
>   <div id="modal-dialog" className="modal" >
>     <button>Ok</button>
>     <button>Cancel</button>
>   </div>
> </FocusTrap>
> ```

**Comment by pradel** [comment]
Thanks for opening this issue, the issue has been closed in the v5 of this package.
📖 You might want to check the **[announcement post](https://www.leopradel.com/blog/react-responsive-modal-v5)** containing the migration guide :)
