### ISSUE TITLE
Problem with scroll position, when you have links.

### ISSUE THREAD

**Issue by bazzzooQa** [pradel/react-responsive-modal#367]
If you have a lot of content for modal so scroll is needed and f.e. you have link (`<a href="/any-link" />`) somewhere at the bottom, the scroll position will be set to this link (does it make sense?).
Can't figure out what the problem is...
Any suggestions?

**Comment by sa77** [comment]
@bazzzooQa I just ran into this .. did you get to a solution?

**Comment by pradel** [comment]
This is because of autofocus, the focus will be set in the modal in the first focusable element when you open the modal. If you want to disable this behavior you can set `focusTrapped` to false.
