### ISSUE TITLE
react-responsive-modal main website not responsive

### ISSUE THREAD

**Issue by Mujaddadi** [pradel/react-responsive-modal#375]
Hi, 
I tried to open this https://react-responsive-modal.leopradel.com/ on many different browsers but it is unresponsive. I remember I faced few this issue months ago but I didn't pursue it. I wonder it's just me because it seems not has reported it yet.

**Comment by pradel** [comment]
Thanks for opening this issue, the website is now online again, I just released the v5 of this package.
📖 You might want to check the **[announcement post](https://www.leopradel.com/blog/react-responsive-modal-v5)** containing the migration guide :)
