### ISSUE TITLE
Firefox: No margin at the bottom of the modal when the content is too big

### ISSUE THREAD

**Issue by rawatnaresh** [pradel/react-responsive-modal#394]
# Bug report

## Describe the bug
When the content of the modal is large enough you won't see any margin at the bottom of the modal. It feels like some of the content is hidden.

## To Reproduce

Have a look at this [example](https://react-responsive-modal.leopradel.com/examples#big-modal) . Open the big modal and then scroll to the bottom of the page. 

## Expected behavior

There should be margin at the bottom of the modal too. 

## System information

- Version of react-responsive-modal: 5.0.2
- Version of react: 16.13.0
- Browser version: any browser

**Comment by pradel** [comment]
@rawatnaresh this is what I see when I open the big modal, maybe I didn't understand your issue but I can't see the problem you are experiencing.

<img width="1676" alt="Screenshot 2020-04-08 at 16 36 37" src="https://user-images.githubusercontent.com/5749437/78796842-2e3dce80-79b7-11ea-8b3b-dd907c2823db.png">

**Comment by rawatnaresh** [comment]
Maybe this issue is only on Firefox.
I'm using Firefox (Version 74.0) and Ubuntu(18.04.4).

**Mobile view in chrome**
![Screenshot from 2020-04-09 10-06-58](https://user-images.githubusercontent.com/29520305/78857803-1ebb9580-7a4a-11ea-9835-73911e5a8016.png)

**Mobile view in Firefox**
![Screenshot from 2020-04-09 10-04-09](https://user-images.githubusercontent.com/29520305/78857815-2bd88480-7a4a-11ea-83bd-a05f304232e3.png)

**Web view in Chrome**
![screen2](https://user-images.githubusercontent.com/29520305/78857862-532f5180-7a4a-11ea-93a8-4370568d20f6.png)

**Web view in Firefox**
![screen3](https://user-images.githubusercontent.com/29520305/78857849-47dc2600-7a4a-11ea-9adc-540b8aeb6eb0.png)

**Comment by pradel** [comment]
Hey, I just published v6.0.0 that is fixing this issue, thanks for reporting
