### ISSUE TITLE
Support remove default classNames

### ISSUE THREAD

**Issue by zhaoyao91** [pradel/react-responsive-modal#405]
# Feature request

## Is your feature request related to a problem? Please describe.

I am building a modal component based on `react-responsive-modal`. I use css-in-js tech to style it. It accepts `classNames` prop which allows me to mount my customized classNames to it, good. But I also want to avoid it being affected by apps which already installed react-responsive-modal and imported the css globally.

## Describe the solution you'd like

Add a prop `removeDefaultClassNames`?

## Additional context

version: 5.0.2

**Comment by zhaoyao91** [comment]
after setting classNames, the modal does not close even if the open is false.

**Comment by pradel** [comment]
@zhaoyao91 If you want the modal to close you will need to add an animation on the exit custom classnames, we listen to the `onAnimationEnd` event to close the modal, could it be why it's currently not closing for you?

**Comment by pradel** [comment]
Closing this one as there was no response. Feel free to reopen
