### ISSUE TITLE
Disable background overlay

### ISSUE THREAD

**Issue by websocket98765** [pradel/react-responsive-modal#406]
## Feature request

Add ability to disable background overlay.

## Use case

I'm using `react-responsive-modal` for standard modals, but I'd like to also use it for an Introduction modal on my website, which would briefly tell about the website and would be fixed positioned to the bottom right, and would would not block the website due to background overlay.

The benefit of doing this as a modal, is it maintains all same styles as existing modals and ability to be closed. (I'm using localStorage to keep it closed if it's already been dismissed.)

## Describe the solution you'd like

Add a prop such as, `disableOverlay:true`, which would default to `false`.

When true, the background overlay would not appear. When combined with the existing `blockScroll:false`, it'd be possible to be possible to achieve the effect effect.

**Comment by pradel** [comment]
@websocket98765 I think you can achieve the same result by passing some custom style to the overlay with `opacity: 0´, would that work for you?

**Comment by pradel** [comment]
Closing as it should be possible with custom css.
Feel free to reopen if not
