### ISSUE TITLE
The background of the page will be changed on toggle modal

### ISSUE THREAD

**Issue by w3ea** [pradel/react-responsive-modal#407]
## Describe the bug
When i open/close modal in my project the background color of the page change.
Just a part of page will be changed.
It's weird
> This problem just appears with the background image.

## To Reproduce
[Take a look at this codesandbox example](https://codesandbox.io/s/background-bug-bilxv)
Scroll to the bottom of page then click to the modal button.
You can see the bottom color was changed.

## To Solve
if remove **position: fix** and **top** from HTML tag, It'll be fixed.
in example, uncomment HTML style in **styles.css** and try again

**Comment by gbilodeau** [comment]
Same here. Seems to be caused by no-scroll, although I'm not clear on why position and top styles need to be set.

**Comment by w3ea** [comment]
> Same here. Seems to be caused by no-scroll, although I'm not clear on why position and top styles need to be set.

Yeah, exactly
[this package (scroll-lock)](https://github.com/FL3NKEY/scroll-lock) is much better for disable scroll

**Comment by pradel** [comment]
@w3ea scroll-lock seems better indeed but the bundle size is quite big for such a small package .. https://bundlephobia.com/result?p=scroll-lock@2.1.4

**Comment by pradel** [comment]
Maybe some parts could be extracted, so we don't have to import the full package?

**Comment by w3ea** [comment]
@pradel Yeah, compare to no-scroll it's big amount

**Comment by pradel** [comment]
Looks like [react-remove-scroll](https://github.com/theKashey/react-remove-scroll) could also be a good option. But same the bundle size is much bigger than no-scroll

**Comment by w3ea** [comment]
It seems good
and this one [react-scrolllock](https://github.com/jossmac/react-scrolllock)
I didn't try this package

**Comment by pradel** [comment]
Hey, I just published v6.0.0, this package is now using body-scroll-lock instead of no-scroll to solve all the scroll related issues. Thanks for the suggestions!
