### ISSUE TITLE
The window is moved to the top, and then the scroll is animated to its original position

### ISSUE THREAD

**Issue by VladimirPolenov** [pradel/react-responsive-modal#410]
## Describe the bug

When you close a modal, the window is moved to the top, and then the scroll is animated to its original position. Window when closing modal twitches top.

**Comment by k4mr4n** [comment]
I don't know the reason behind adding `top: Xpx` to html element but I think we can fix this by adding padding-top: Xpx to the  html element

**Comment by pradel** [comment]
Hey all, I just published v6.0.0, this package is now using body-scroll-lock instead of no-scroll to solve all the scroll related issues.
