### ISSUE TITLE
handleModalEvent with onMouseDown make a bug

### ISSUE THREAD

**Issue by little-buddy** [pradel/react-responsive-modal#421]
https://github.com/pradel/react-responsive-modal/blob/e6c7027a561473fc9a72d13a8ba37ec83bd0a505/src/index.tsx#L311

When I use stopPropagation in childComponent of modal by onClick,  It's must double click to close modal.
Than I discover it. It's difficult to use. 
😂

**Comment by pradel** [comment]
Hey sorry for not taking a look earlier, can you please provide a reproduction?

**Comment by pradel** [comment]
Closing this one as there was no response. Feel free to reopen
