### ISSUE TITLE
Window not scrollable after navigating routes

### ISSUE THREAD

**Issue by matbrady** [pradel/react-responsive-modal#430]
# Bug report

This issue has been reported before.
- https://github.com/pradel/react-responsive-modal/issues/63
- https://github.com/pradel/react-responsive-modal/issues/239

## Describe the bug

When navigating to a new route from within a modal, the browser window is no longer able to be scrolled. 

## To Reproduce

On a page large enough to scroll, create a Modal containing a link to another route. Navigate to the new route. The new view will not be scrollable. The only way around it seems to be to create a setTimeout that navigates to the new route after the modal exit animation has finished. 

## Expected behavior

The html styles should be removed before the Modal is unmounted.

## Example of issue

**Stackblitz**:  https://stackblitz.com/edit/react-gzs6jw?file=src/Page1.js

<img width="300" src="https://user-images.githubusercontent.com/1770862/97032138-53e38d00-152f-11eb-8a4c-7aa604d50d7a.gif" />

## System information

- Version of react-responsive-modal: 5.1.1
- Version of react: ^16.13.1
- Browser version: *

**Comment by kuomingwu** [comment]
same issue +1 and setTimeout is workaround !

**Comment by pradel** [comment]
@matbrady Thanks for reporting the issue, should be fixed in v5.2.1 :)
