### ISSUE TITLE
Next.js: page won't load if modal is showing at page load

### ISSUE THREAD

**Issue by giraffesyo** [pradel/react-responsive-modal#432]
# Bug report

Thank you very much for the easy to use component. The following isn't an important bug to me, but just letting you know as an FYI because I ran into it while testing.

## Describe the bug

Using next.js, if you have the modal open at page load you will get the following error:

> Server Error
> Error: Target container is not a DOM element.
> 
> This error happened while generating the page. Any console logs will be displayed in the terminal window.

## To Reproduce

Create a next.js project, use the following hook:

```javascript
  const [modalIsOpen, setModalIsOpen] = React.useState(true)
```

And use that state within your modal
```javascript
<Modal open={modalIsOpen} center onClose={() => setModalIsOpen(false)}>Content</Modal>
```

## Expected behavior

Page loads, with modal open. 

## System information

- Version of react-responsive-modal: 5.2.0
- Version of react: 16.13.1
- Browser version: Chrome 86
- Next.js version 10.0.0

**Comment by pradel** [comment]
Thanks for reporting the issue, should be fixed in v5.2.1 :)
