### ISSUE TITLE
Custom styling

### ISSUE THREAD

**Issue by Paolo5150** [pradel/react-responsive-modal#452]
# Bug report

I'm simply trying to apply custom styling and it doesn't seem to work

# Describe the bug

I just followed the tutorial on the website: apply a custom class name and style the class in the css.
The modal just never changes.

## To Reproduce

Apply custom class name
Restyle in the css
Reload page (shift F5)

## Expected behavior

The modal should have the new style applied

## Screenshots

This should have a blue background and red text 
![image](https://user-images.githubusercontent.com/8026573/99163477-edbde480-273f-11eb-869e-f613ba797f31.png)

## System information

- Version of react-responsive-modal: 5.2.6
- Version of react: 17.0.1
- Browser version: Chrome  86.0.4240.193

**Comment by pradel** [comment]
@Paolo5150 can you share the code you have for the modal and the css?

**Comment by pradel** [comment]
Closing this one as there was no response. Feel free to reopen
