### ISSUE TITLE
Issue when click close Icon...

### ISSUE THREAD

**Issue by webmas0124** [pradel/react-responsive-modal#460]
Hi
I am very happy to using react-responsive-modal.
I used this at several projects and I find one issue.

As you can see below screenshots, if I click close Icon I am getting error.

![Screen Shot 2020-11-18 at 11 41 19 PM](https://user-images.githubusercontent.com/57678421/99537703-bd07d480-29f7-11eb-972d-04b7ac92e6f2.png)

![Screen Shot 2020-11-18 at 11 42 00 PM](https://user-images.githubusercontent.com/57678421/99538077-2b4c9700-29f8-11eb-89c5-892ddb266c81.png)

I tried to solve this issue but not yet.
Anybody can help me?

Thank you.

**Comment by pradel** [comment]
@webmas0124 which version are you using? This issue was fixed in v5.2.6.

**Comment by webmas0124** [comment]
@pradel
I changed to v5.2.6 and it works fine.
Thank you.
