### ISSUE TITLE
Modal dont open but a bottom of page 

### ISSUE THREAD

**Issue by logicappsource** [pradel/react-responsive-modal#471]
# Bug report

## Describe the bug
The modal dont open, but put text at bottom,

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository.

## Expected behavior
To open modal correctly 

## Screenshots

<img width="1609" alt="Screenshot 2021-03-28 at 20 32 54" src="https://user-images.githubusercontent.com/14986750/112763515-00f19280-9005-11eb-89c7-4df66782c2f2.png">

## System information

- Version of react-responsive-modal: 
-    "react-responsive-modal": "^6.0.1",
- Version of react: 
-     "react": "^16.8.0",
- Browser version: [e.g. Safari 16.8.1]
Chrome safari latest

**Comment by pradel** [comment]
You need to import the css file for it to work, just add
```
import 'react-responsive-modal/styles.css';
```
