### ISSUE TITLE
Multiple Modals On One Screen

### ISSUE THREAD

**Issue by chusyntax** [pradel/react-responsive-modal#481]
I am trying to have multiple modal buttons on one page and when I click on a different modal, it displays its own unique modal.

I tried this by changing the names of the state variables but that didn't work, it actually only opened up the first modal.

Here is a snippet of the code:

`const Projects = () => {
         

 const [open, setOpen] = useState(false);
const [open2, setOpen2] = useState(false);

  
  const onOpenModal = () => setOpen(true);
  const onCloseModal = () => setOpen(false);

  const onOpenModal2 = () => setOpen(true);
  const onCloseModal2 = () => setOpen2(false);

  return (
    <div className='modals'>

    <div>
      <button onClick={onOpenModal}>Open modal 1</button>
      <Modal open={open} onClose={onCloseModal} center>
        <h2>Simple centered modal 1</h2>
        <p>
          Lorem ipsum dolor sit amet,   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam
          pulvinar risus non risus hendrerit venenatis. Pellentesque sit amet
          hendrerit risus, sed porttitor quam.
        </p>
      </Modal>
    </div>

     <div>
      <button onClick={onOpenModal2}>Open modal 2</button>
      <Modal open={open2} onClose={onCloseModal2} center>
        <h2>Simple centered modal 2</h2>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam
          pulvinar risus non risus hendrerit venenatis. Pellentesque sit amet
          hendrerit risus, sed porttitor quam.
        </p>
      </Modal>
    </div>

    </div>
    
  );
 };

export default Projects`

**Comment by pradel** [comment]
you have to replace `const onOpenModal2 = () => setOpen(true);` by `const onOpenModal2 = () => setOpen2(true);`

**Comment by chusyntax** [comment]
Yes that worked. Thank you!
