### ISSUE TITLE
Enable click on overlay to close on iOS

### ISSUE THREAD

**Issue by johncookv** [pradel/react-responsive-modal#49]
**Summary**:
On iOS 11, with onClickOverlay enabled, when the user taps on an overlay, the overlay doesn't close.

Seems similar to an issue another react modal library has. The relevant links are below.

https://github.com/reactjs/react-modal/issues/301
https://github.com/reactjs/react-modal/pull/304

**Comment by peterlazzarino** [comment]
Seems like the overlay needs a cursor: pointer to get around the bug based on those issues which is kinda crazy.

**Comment by pradel** [comment]
That's a really weird issue unfortunately I don't have an ios device to test this so I would accept a pull request for that.
It would be better to not have the overlay as a pointer cursor ..

**Comment by johncookv** [comment]
We were able to fix the issue by updating your library in our project from onMouseDown to onClick to close the overlay. I was going to update the code and submit a pull request, but it looks like onMouseDown was used to fix another bug:

[https://github.com/pradel/react-responsive-modal/issues/16](url)

If I can find a way to fix it which doesn't affect bug 16, I'll submit the pull request.

**Comment by pradel** [comment]
Thanks @johncookv!

**Comment by pradel** [comment]
this issue should now be fixed see https://github.com/pradel/react-responsive-modal/releases/tag/v3.0.0
