### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by hudochenkov** [pradel/react-responsive-modal#496]
Please add support for React 18:

- [Changelog](https://github.com/facebook/react/blob/main/CHANGELOG.md#1800-march-29-2022)
- [Release post](https://reactjs.org/blog/2022/03/29/react-v18.html)
- [How to Upgrade to React 18](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html)

**Comment by Globebyte** [comment]
In the meantime, will it work if you ignore the dependency limitation ?

**Comment by Maciej916** [comment]
It is only for me or modal is flickering when closing in React 18

**Comment by AtuHQ** [comment]
Any updates on this case?

**Comment by pradel** [comment]
Published as 6.4.1
