### ISSUE TITLE
Modal bugs on multiple browsers

### ISSUE THREAD

**Issue by gilnetoglartek** [pradel/react-responsive-modal#56]
## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal | 2.0.0 |
| React                  | 16.2.0 |
| browser                | Chrome (64.0.3282.186) / Microsoft Edge (41.16299.248.0) |

Hey there.
We've been using your modals for some time now, created a few for our product, but have been running into a few UI glitches. I'll ennumerate below, please tell me what you think.

First of all, on our code, we create specific components for each modal we use, at least for the time being. That means that, in a main component X, instead of importing your modal solution, we import our modal component, which in turn renders your modal solution with our specified fields.

With that said:

1. This is our main screen for one of the menu items:
![image](https://user-images.githubusercontent.com/35693671/36790653-7794ed5e-1c8d-11e8-8c30-e63d4ab9d084.png)
When we click 'Create Task', a modal appears, but whenever it appears, a small space on the right side gets reserved for the modal scroll, which is never used:
![image](https://user-images.githubusercontent.com/35693671/36790723-a9ef4c86-1c8d-11e8-9db6-db4524bf15a5.png)
This gets corrected whenever we close the modal, but it looks obviously bad to have it like this. Do you have any idea as to why this happens and, if so, any solution?

2. If you check the second image I attached here, you'll see that the navbar on the left seems to be in front of the modal, not behind it. Is there any way to put it behind the modal too? I'm not yet aware on how the navbar was implemented, but I can look into it if you need some more guidance from our side.

3. On our splash screen, we're showing a number of open tasks, onto which one can go and check its information. This, of course, enables a scroll on our browser:
![image](https://user-images.githubusercontent.com/35693671/36790900-2a57bcd2-1c8e-11e8-8e4c-a642b4947774.png)
(please don't mind the navbar, we know it should be dragged down to follow the viewport...)
However, if we scroll down and try to open a modal after scrolling, i.e. on any of the tasks shown above, this happens:
![image](https://user-images.githubusercontent.com/35693671/36790958-5a61dd72-1c8e-11e8-89a2-dc7c7cd3809d.png)
Not only does the scroll reserved space appear, but the whole screen doesn't follow the modal appearance. This gets corrected as soon as we close the modal, and we return to the place where we were.

Bear in mind that these issues appear on both Chrome and Edge, the browsers we have installed at the moment.
I hope I wasn't too confusing about these issues. Feel free to request more information if you need.

Thanks in advance,
Gil

**Comment by pradel** [comment]
Hey, thanks for the detailed errors!

1. This should definitely not happen could you provide a codesandbox example for that?
2. You should check the z-index property of your navbar and reduce it (or change the modal z-index)
3. Really weird error .. Are you using a theme you bought? Same I will need a reproducible example on codesandbox in order to debug it.

Without a folder that will show me the errors to be able to debug them I will not be able to help you :(

**Comment by gilnetoglartek** [comment]
Thanks for the quick response. I'll start my answers from the end.

Yes, we've bought a theme, called Inspinia, and I've been working on this after the theme layer was inserted. So I'm not really sure what impact this has on our environment, but since I can't seem to reproduce these errors on the codesandbox, I can only assume that these errors are from something the theme is importing.

Regarding problem (2), as soon as I changed the zIndex to a lower value, the modal was correctly shown. Thanks for the tip.

Gil

**Comment by gilnetoglartek** [comment]
Hey there,

I've disabled the CSS we bought and, lo and behold, the errors vanished...
In the meantime I've opened a thread with their support team, so I'll be talking to them trying to figure it out.

Anyways, sorry to bother you, and thank you for your tips!

**Comment by pradel** [comment]
Okay perfect let me know how it goes :) can I close the issue?
