### ISSUE TITLE
Using the ESC key with two modals open, closes them both.

### ISSUE THREAD

**Issue by brennanpayne** [pradel/react-responsive-modal#57]
## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |  2.0.0       |
| React                  |  16.2.0       |
| browser                |  Chrome       |

Hello,

Right now, when you open two modals (with the `closeOnEsc` prop set to `true), hitting the escape key closes them both.

[Here's a sandbox to see it happen](https://codesandbox.io/s/q8q67zl4mw
)

Any recommendations on how to remedy this?  Is this something that should go in the library?

Thanks!

**Comment by pradel** [comment]
Hey, yeah this is not handled yet, in order to do that we will need a manager that will keep track of all opened modals.
So this will require some work in order to be able to fix that :)
