### ISSUE TITLE
[feat request] Option to keep modal dom elements on page even if it is closed

### ISSUE THREAD

**Issue by corysimmons** [pradel/react-responsive-modal#76]
Could be done by just defaulting opacity to 0 and z-index to -9999999.

The reason it'd be handy is for things like FirebaseUI (needs a dom element to watch).

**Comment by pradel** [comment]
I understand, but I created this package to not mount the node for performance reasons, I often have to create hundred of modals in the same view, to not render them is a big win for performance.

**Comment by pradel** [comment]
I Will anyway see if there is a simple to do that, if I find something will tell you

**Comment by corysimmons** [comment]
@pradel Okay, thanks. I just ended up making a faux modal that lives in my root app for my purposes. It works, but is definitely a smell since I'm already using a modal lib w/ styles/animations.
