### ISSUE TITLE
Click on scroll bar still closes modal if page content is short

### ISSUE THREAD

**Issue by timkingman** [pradel/react-responsive-modal#81]
I'm still seeing this issue (#43) on 2.0.1, with Chrome (65.0.3325.181 x64) on Windows (7).
My modal content is tall, but my main page doesn't scroll. Clicking on the scroll bar still closes the window in Peter's codesandbox in the first comment, even after switching it to r-r-m 2.0.1.

I can also reproduce this on https://react-responsive-modal.leopradel.com/ after removing everything below the examples so the main page doesn't scroll.
1. https://react-responsive-modal.leopradel.com/
2. In Chrome dev tools, run:
`$('.main-content').removeChild($('.main-content > div:not(.examples)')); 
$('.main-content').removeChild($('.main-content > footer'))`
3. If necessary, resize your window so there are no scroll bars.
4. Click the Open button for the "Big modal" example.
5. Click on the scroll bar that just appeared and try to scroll.

Expected: page scrolls with modal in it. (This works when scrolling with a mouse wheel.)
Actual: modal closes.

It looks like when the main page content doesn't scroll, `document.documentElement.offsetWidth` matches `window.innerWidth` as the full width of the window. When the main page content has a scrollbar, these widths differ and Peter's patch works to detect clicks in the vertical scrollbar.

In my case, where the page doesn't scroll but the modal causes a scrollbar to appear, the `.scrollWidth` of the overlay is less than `window.innerWidth`. I think this makes sense, because the modal is nested inside the overlay, so if the modal's content is tall, the overlay gets a scroll bar.

I've only tested my pull request #75 in Chrome 65 and IE 11, but it looks good on both.

**Comment by pradel** [comment]
Hey thanks for your pr! I will take a look at it and get back to you shortly :)

**Comment by pradel** [comment]
Hey thank you very much for the pr, but I took another approach to resolve the issue and published a v3.0.0 version see https://github.com/pradel/react-responsive-modal/releases/tag/v3.0.0.
Let me know if the issue is not fixed :)
