### ISSUE TITLE
Pass HTML in a variable

### ISSUE THREAD

**Issue by juancaacuna** [pradel/react-responsive-modal#85]
Hi! Is there a way to pass HTML in a variable?
Example:

```this.setState({ htmlContent: '<div>Hello World</div>' }); ```

and then
```
<Modal open={this.state.open} onClose={this.onCloseModal} little>
   { this.state.htmlContent }
</Modal>
```

**Comment by pradel** [comment]
you will have to use the react `dangerouslySetInnerHTML` to do that `<div dangerouslySetInnerHTML={{__html: this.state.htmlContent}} />`
