### ISSUE TITLE
Demo is not working for me

### ISSUE THREAD

**Issue by paneq** [pradel/react-responsive-modal#96]
Only the "CSS modal" shows up

## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| browser                |     Chrome on Mac    |

**Comment by pradel** [comment]
Yeah I know .. that it's because I am now using the new react lifecycles on the master branch which are not compatible with jss yet.
Will have to find a way to make the demo work without jss.
Thanks for reporting!
